name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          set -e

          cd /www/wwwroot/qurani.link.id

          echo "[github-actions] >> Pulling latest changes from main branch..."
          git pull origin main

          echo "[github-actions] >> Installing Node.js dependencies..."
          export NVM_DIR="/www/server/nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 22
          npm install --legacy-peer-deps

          echo "[github-actions] >> Installing PHP dependencies..."
          composer install --no-dev --optimize-autoloader

          echo "[github-actions] >> Building for production..."
          npm run build

          echo "[github-actions] >> Deployment completed successfully."
        EOF
